apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: letsencrypt-cloudflare
spec:
    acme:
        server: https://acme-v02.api.letsencrypt.org/directory
        email: yurii.hasko@lnu.edu.ua
        privateKeySecretRef:
            name: letsencrypt-cloudflare
        solvers:
            - dns01:
                  cloudflare:
                      email: yurii.hasko@lnu.edu.ua
                      apiTokenSecretRef:
                          name: cloudflare-api-key-secret
                          key: cloudflare_api_token