apiVersion: apps/v1
kind: Deployment
metadata:
  name: orleans-client
  labels:
    app: kubeclient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubeclient
  template:
    metadata:
      labels:
        app: kubeclient
    spec:
      serviceAccountName: orleansclient
      containers:
        - name: orleansclient
          image: webprojectdev.azurecr.io/kube-silo-host:0.1.9
          imagePullPolicy: Always