apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secret.yaml

helmCharts:
    - name: external-dns
      version: 7.1.2
      repo: https://charts.bitnami.com/bitnami
      releaseName: external-dns
      namespace: kube-system
      valuesFile: values.yaml

transformers:
  - envsubst.yaml