apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
    - traefik-dashboard-ingress.yaml
    - traefik-dashboard-service.yaml
    - traefik-dashboard-middleware.yaml
    - basic-auth-middleware.yaml
    - basic-auth-secret.yaml

helmCharts:
    - name: traefik
      version: 26.0.0
      repo: https://traefik.github.io/charts
      releaseName: traefik
      namespace: kube-system
      valuesFile: values.yaml

transformers:
  - envsubst.yaml